const DIFFICULTY = 2;
const MINE_RATE = 10000; // 1000 = 1s for a block 
const INITIAL_BALANCE = 500;
const MINING_REWARD = 50;

module.exports = { DIFFICULTY, MINE_RATE, INITIAL_BALANCE, MINING_REWARD };