apiVersion: apps/v1
kind: Deployment
metadata:
  name: neptune-deployment
spec:
  selector:
    matchLabels:
      app: neptune
  replicas: 3
  template:
    metadata:
      labels:
        app: neptune
    spec:
      containers:
        - name: neptune
          image: theoneandonlywoj/neptune:1.0
          env:
            - name: SECRET_KEY_BASE
              value: iqUewr+tA5s0RsHIgOwgl9PzvSjZZ+3c03XwEG+P3gZMNRWZv/CEhxDbMi5eBGZb
            - name: PORT
              value: "4000"
            - name: DATABASE_URL
              value: ecto://postgres:mysecretpassword@postgres-service/neptune_prod
            - name: CLUSTERING_STRATEGY
              value: kubernetes_dns
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
